applicantapp/urls.py
"""
Urls for applicant
"""
from django.urls import path

from applicantapp.views import (
    ProfileView, ResumeList, CreateResume, UpdateResume, JobListDetail, JobSearchList, ResponceHr,
    ResponceJobDetail, FavoriteJobList, AddDeleteResumeToFavorites
)


app_name = 'applicantapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('createresume/', CreateResume.as_view(), name='createresume'),
    path('resume-list/', ProfileView.as_view(), name='resume-list'),
    path('resumes-list/update_resume/<int:pk>/', UpdateResume.as_view(), name='update_resume'),
    path('job-search-list/', JobSearchList.as_view(), name='job_search_list'),
    path('job-detail/<int:pk>/', JobListDetail.as_view(), name='job-list-detail'),
    path('responce-job/', ResponceHr.as_view(), name='responce_resume_list'),
    path('responce-job-detail/<int:pk>/', ResponceJobDetail.as_view(), name='respince_job_detail'),
    path('favorite/<int:pk>/', AddDeleteResumeToFavorites.as_view(), name='favorite'),
    path('favorites-job-list', FavoriteJobList.as_view(), name='favorites-job-list'),

]

companyapp/urls.py
from django.urls import path

from .views import (
    ProfileView, CompanyDetailView, CompanyUpdateView, JobCreateView, JobDetailView,
    JobUpdateView, JobListView, ResumeListHR, ResumeListDetail, ResumeSearchList, ResponceRec, RespJobDetail,
    AddDeleteVacancyToFavorites, FavoriteResumeList
)


app_name = 'companyapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/card/', CompanyDetailView.as_view(), name='card'),
    path('<int:pk>/card/edit/', CompanyUpdateView.as_view(), name='edit'),
    path('<int:pk>/job/new/', JobCreateView.as_view(), name='new-job'),
    path('job/<int:pk>/edit/', JobUpdateView.as_view(), name='edit-job'),
    path('job/<int:pk>/detail/', JobDetailView.as_view(), name='detail-job'),
    path('job-list/', JobListView.as_view(), name='job-list'),
    path('resume-list/', ResumeListHR.as_view(), name='resume-list'),
    path('resume-detail/<int:pk>/', ResumeListDetail.as_view(), name='resume-list-detail'),
    path('resume-search/', ResumeSearchList.as_view(), name='resume_search'),
    path('responce-rec/', ResponceRec.as_view(), name='responce_recrut_list'),
    path('responce/<int:pk>/detail/', RespJobDetail.as_view(), name='responce_job_detail'),
    path('favorite/<int:pk>/', AddDeleteVacancyToFavorites.as_view(), name='favorite'),
    path('favorites-resume-list', FavoriteResumeList.as_view(), name='favorites-resume-list'),
]

mainapp/urls.py
from django.urls import path

from .views import Index, AllNews, NewsDetail, InviteView, InviteFromHr, statusInviteUpdate

app_name = 'mainapp'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('news/', AllNews.as_view(), name='news_all'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('ivnite/<int:job_id>/', InviteView.as_view(), name='invite_user'),
    path('invetofromhr/<int:resume>/', InviteFromHr.as_view(), name='invite_from_hr'),
    path('statusinvupdate/<int:pk>/', statusInviteUpdate, name='status_invite_update'),
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
    path('moder/', include('moderapp.urls')),
    path('messenger/', include('messenger.urls'))

]

applicantapp/models.py
"""
Models for applicant
"""
from django.db import models

from authapp.models import MyUser


class StatusResume(models.Model):
    class Meta:
        verbose_name = 'Статус Резюме'
        verbose_name_plural = 'Статусы Резюме'

    status_name = models.CharField(max_length=250, blank=True, null=True)

    def __repr__(self):
        return self.status_name

    def __str__(self):
        return self.status_name


class Resume(models.Model):
    """
    Applicants resume
    """
    def user_directory_path(instance, filename):
        return f'resume/user_{instance.user.id}/{filename}'

    class Meta:
        get_latest_by = '-updated_at'
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'

    STATUS = (
        ('0', 'Отклонено модератором'),
        ('1', 'Заготовка'),
        ('2', 'На модерации'),
        ('3', 'Опубликовано'),
        ('4', 'Черновик'),
        ('5', 'Скрыто'),
        ('9', 'Удалено'),
    )

    EMPLOYMENT_CHOICES = (
        ('FT', 'Полная занятость'),
        ('PT', 'Частичная занятость'),
        ('PW', 'Проектная работа'),
        ('VL', 'Волонтерство'),
        ('WP', 'Стажировка'),
    )

    WORK_SCHEDULE_CHOICES = (
        ('FD', 'Полный день'),
        ('SSCH', 'Сменный график'),
        ('FSCH', 'Гибкий график'),
        ('RW', 'Удаленная работа'),
        ('RBW', 'Вахтовый метод'),
    )

    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE, null=True)
    headline = models.CharField(max_length=255, blank=False, verbose_name='Заголовок')
    status = models.CharField('Статус', max_length=1, choices=STATUS, default='1', db_index=True)
    first_name = models.CharField(max_length=255, blank=False, verbose_name='Имя')
    surname = models.CharField(max_length=255, blank=False, verbose_name='Фамилия')
    salary = models.PositiveIntegerField(blank=True, null=True,
                                         verbose_name='Желаемая заработная плата')
    date_of_birth = models.DateField(blank=False, verbose_name='Дата рождения')
    city = models.CharField(max_length=255, blank=False, verbose_name='Город')
    user_pic = models.ImageField(upload_to=user_directory_path, blank=True,
                                 null=True, verbose_name='Фото')
    links = models.CharField(max_length=255, blank=True, null=True,
                             verbose_name='Ссылка на профиль в соц. сетях или сайт')
    employment = models.CharField(max_length=20, blank=False, choices=EMPLOYMENT_CHOICES,
                                  verbose_name='Занятость')
    work_schedule = models.CharField(max_length=20, blank=False, choices=WORK_SCHEDULE_CHOICES,
                                     verbose_name='График работы')
    about_me = models.TextField(blank=True, null=True, verbose_name='Обо мне')
    key_skills = models.CharField(max_length=255, blank=True, null=True,
                                  verbose_name='Ключевые навыки')
    phone = models.CharField(max_length=20, blank=False, verbose_name='Телефон')
    moder_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')
    views_count = models.PositiveIntegerField(blank=True, default=0,
                                              verbose_name='Кол-во просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __repr__(self):
        return self.headline

    def __str__(self):
        return self.headline

    def is_favorite(self, user):
        return bool(FavoritesResume.objects.filter(user=user, resume=self).count())


class Experience(models.Model):
    """
    Applicant work experience
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыт работы'

    resume = models.ForeignKey(Resume, related_name='experience', on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255, blank=False, verbose_name='Название компании')
    company_link = models.CharField(max_length=255, blank=True, null=True,
                                    verbose_name='Сайт компании')
    position = models.CharField(max_length=255, blank=False, verbose_name='Дожность')
    data_from = models.DateField(blank=False, verbose_name='Дата начала работы')
    data_to = models.DateField(blank=False, verbose_name='Дата окончания работы')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __repr__(self):
        return self.company_name

    def __str__(self):
        return self.company_name


class Education(models.Model):
    """
    Applicant education institutions
    """

    EDUCATION_CHOICES = (
        ('SECONDARY', 'Среднее'),
        ('SPECIAL_SECONDARY', 'Среднее специальное'),
        ('UNFINISHED_HIGHER', 'Неоконченное высшее'),
        ('HIGHER', 'Высшее'),
    )

    GRADE = (
        ('BACHELOR', 'Бакалавр'),
        ('MASTER', 'Магистр'),
        ('CANDIDATE', 'Кандидат наук'),
        ('DOCTOR', 'Доктор наук'),
    )

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Образовательное учреждение'
        verbose_name_plural = 'Образовательные учреждения'

    resume = models.ForeignKey(Resume, related_name='education', on_delete=models.CASCADE)
    education_type = models.CharField(max_length=20, blank=False, choices=EDUCATION_CHOICES,
                                      null=True, verbose_name='Тип образования')
    grade = models.CharField(max_length=20, blank=True, choices=GRADE, verbose_name='Степень')
    name = models.CharField(max_length=255, blank=False, verbose_name='Название учреждения')
    specialization = models.CharField(max_length=255, blank=False, verbose_name='Специальность')
    year_of_ending = models.PositiveIntegerField(blank=False, verbose_name='Год окончания')

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name


class FavoritesResume(models.Model):
    """
    Favorites Resume
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Избранные резюме'
        verbose_name_plural = 'Избранные резюме'
        unique_together = (("user", "resume"),)

    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE, null=True)
    resume = models.ForeignKey(to=Resume, on_delete=models.CASCADE)

companyapp/models.py
from django.db import models, transaction
from django.urls import reverse_lazy

from authapp.models import MyUser


class Company(models.Model):
    """
    Компания-работодатель
    """
    def user_directory_path(instance, filename):
        return f'logo/user_{instance.user.id}/{filename}'

    STATUS = (
        ('0', 'Отклонена модератором'),
        ('1', 'Заготовка'),
        ('2', 'На модерации'),
        ('3', 'Опубликована'),
        ('4', 'Черновик'),
        ('9', 'Удалена'),
    )

    user = models.OneToOneField(to=MyUser, on_delete=models.PROTECT, related_name='company', verbose_name="Пользователь", null=True)
    name = models.CharField('Наименование компании', max_length=255, blank=False, db_index=True)
    status = models.CharField('Статус', max_length=1, choices=STATUS, default='1', db_index=True)
    logo = models.ImageField('Логотип', upload_to=user_directory_path, blank=True, null=True)
    headline = models.CharField('Слоган', max_length=255, blank=True)
    short_description = models.CharField('Краткое описание', max_length=255, blank=False)
    detail = models.TextField('Подробное описание', blank=True)
    location = models.CharField('Местонахождение', max_length=255, blank=False, db_index=True)
    link = models.CharField('Ссылка на сайт / соц.сеть', max_length=255, blank=True, null=True)
    moder_comment = models.TextField('Заключение модератора', blank=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)
    views_count = models.PositiveIntegerField('Число просмотров', default=0)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    def views_counter(self):
        """ Счетчик просмотров карточки компании """
        if Company.objects.filter(pk=self).exists():
            with transaction.atomic():
                self = Company.objects.get(id=self)
                self.views_count += 1
                self.save()


def create(instance):
    """
    Создание заготовки компании по сигналу вновь зарегистрированного работодателя
    """
    Company.objects.create(user=instance,)


class Job(models.Model):
    """
    Вакансии
    """
    STATUS = (
        ('0', 'Отклонена модератором'),
        ('1', 'Заготовка'),
        ('2', 'На модерации'),
        ('3', 'Опубликована'),
        ('4', 'Черновик'),
        ('5', 'Скрыта'),
        ('6', 'Закрыта'),
        ('9', 'Удалена'),
    )

    GRADE = (
        ('TR', 'Trainee'),
        ('JR', 'Junior'),
        ('MD', 'Middle'),
        ('SR', 'Senior'),
        ('TL', 'TeamLead'),
        ('TD', 'CTO'),
    )

    CATEGORY = (
        ('FLS', 'Full Stack'),
        ('FED', 'Front-end'),
        ('BED', 'Back-end'),
        ('SW', 'Software'),
        ('AI', 'AI & ML'),
        ('BD', 'Big Data'),
        ('AND', 'Android'),
        ('IOS', 'iOS'),
        ('IOT', 'IoT'),
        ('QA', 'QA Engineer'),
        ('GD', 'GameDev'),
        ('PJM', 'Project Manager'),
        ('PDM', 'Product Manager'),
    )

    EMPLOYMENT = (
        ('FT', 'Полная занятость'),
        ('PT', 'Частичная занятость'),
        ('PW', 'Проектная работа'),
        ('VL', 'Волонтерство'),
        ('WP', 'Стажировка'),
    )

    WORK_SCHEDULE = (
        ('FD', 'Полный день'),
        ('SSCH', 'Сменный график'),
        ('FSCH', 'Гибкий график'),
        ('RW', 'Удаленная работа'),
        ('RBW', 'Вахтовый метод'),
    )

    EXPERIENCE = (
        ('WE', 'Без опыта'),
        ('SM', 'До 1 года'),
        ('MD', '1-3 года'),
        ('BG', 'Более 3 лет'),
    )

    company = models.ForeignKey(to=Company, on_delete=models.PROTECT, related_name='jobs', verbose_name='Компания', null=True)
    status = models.CharField('Статус', max_length=1, choices=STATUS, default='1', db_index=True)
    grade = models.CharField('Классность', max_length=2, choices=GRADE, db_index=True)
    category = models.CharField('Категория', max_length=3, choices=CATEGORY, db_index=True)
    salary = models.PositiveIntegerField('Зарплата', null=True, blank=True, db_index=True)
    city = models.CharField('Город', max_length=255, blank=False, db_index=True)
    employment = models.CharField('Тип занятости', max_length=2, choices=EMPLOYMENT, db_index=True)
    work_schedule = models.CharField('График работы', max_length=4, choices=WORK_SCHEDULE, db_index=True)
    experience = models.CharField('Опыт работы', max_length=2, choices=EXPERIENCE, db_index=True)
    short_description = models.CharField('Краткое описание', max_length=255, blank=False)
    description = models.TextField('Подробное описание', blank=True, null=True)
    skills = models.CharField('Навыки', max_length=255, blank=True)
    moder_comment = models.TextField('Заключение модератора', blank=True, null=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)
    views_count = models.PositiveIntegerField('Число просмотров', default=0)

    class Meta:
        ordering = ('status', '-created_at',)
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

    def __repr__(self):
        dev, category = (
            'Разработчик', self.get_category_display()
        ) if self.grade not in ['TL', 'TD'] else ('', '')
        grade = self.get_grade_display()
        return f'{grade} {category} {dev}'

    def __str__(self):
        dev, category = (
            'Разработчик', self.get_category_display()
        ) if self.grade not in ['TL', 'TD'] else ('', '')
        grade = self.get_grade_display()
        return f'{grade} {category} {dev}'

    def get_absolute_url(self):
        return reverse_lazy('companyapp:profile', args=[self.company.pk])

    def change_status(self, status):
        """ Смена статуса вакансии """
        with transaction.atomic():
            self = Job.objects.get(id=self)
            self.status = status
            self.save()

    def is_favorite(self, user):
        return bool(FavoritesVacancies.objects.filter(user=user, job=self).count())


class FavoritesVacancies(models.Model):
    """
    Favorites Vacancies
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Избранные вакансии'
        verbose_name_plural = 'Избранные вакансии'
        unique_together = (("user", "job"),)

    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE, null=True)
    job = models.ForeignKey(to=Job, on_delete=models.CASCADE)

templates/applicantapp/favorite_job_list.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <header class="page-header bg-img size-lg">
        <div class="container no-shadow">
            <h1 class="text-center">Личный кабинет - {{ user.email }}</h1>
            {% include 'inc/applicant_header_menu.html' %}
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main container -->
    <main>
        <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row item-blocks-connected">
                    <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row item-blocks-connected">
                    <div class="col-xs-12">
                        <div class="item-block">

                        {% include 'inc/job_list.html' %}

                        </div>
                    </div>
                </div>

            </div>

        </section>
                </div>
            </div>
        </section>
    </main>
    <!-- END Main container -->
{% endblock %}

{% block footer %} {% endblock %}

templates/applicantapp/job_search.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <header class="page-header bg-img size-lg">
        <div class="container no-shadow">
            <h1 class="text-center">Личный кабинет - {{ user.email }}</h1>
            {% include 'inc/applicant_header_menu.html' %}
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main container -->
    <main>
        <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row item-blocks-connected">
                    <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row item-blocks-connected">
                    <div class="col-xs-12">
                        <div class="item-block">
                            <div class="search">
                                    <form class="search-form" action="{% url 'applicantapp:job_search_list' %}" method="get">{% csrf_token %}
                                        {{ form.as_p }}
                                        <button class="grp-search-button" type="submit">Поиск</button>
                                    </form>
                            </div>
                        {% include 'inc/job_list.html' %}
                        </div>
                    </div>
                </div>

            </div>

        </section>
                </div>
            </div>
        </section>
    </main>
    <!-- END Main container -->
{% endblock %}

{% block footer %} {% endblock %}

templates/applicantapp/profile.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <header class="page-header applicant bg-img size-lg">
        <div class="container no-shadow">
            <h1 class="text-center">Личный кабинет - {{ user.email }}</h1>
            {% include 'inc/applicant_header_menu.html' %}
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main container -->
    <main>
        <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-right">
                        <br>
                        <a class="btn btn-primary btn-sm" href="{% url 'applicantapp:createresume'%}">Добавить резюме</a>
                    </div>
                    {% for resume in resume_list %}
                        <div class="col-xs-12">
                            <div class="item-block">
                                <header>
                                    <div class="hgroup">
                                        <h5><a href="{% url 'applicantapp:update_resume' resume.pk %}">{{ resume }} </a></h5>
                                    </div>
                                    <div class="header-meta">
                                        <span ><i class="fa fa-map-marker"></i> {{ resume.city }} </span><br>
                                        <span class="rate">{{ resume.salary }} руб. </span>
                                        <span> Просмотров : {{ resume.views_count }} </span><br>
                                        {% if resume.status == "0" %}
                                            <span> Статус : Отклонена модератером </span>
                                        {% elif resume.status == "1" %}
                                            <span> Статус : Заготовка </span>
                                        {% elif resume.status == "2" %}
                                            <span> Статус : На модерации </span>
                                        {% elif resume.status == "3" %}
                                            <span> Статус : Опубликована </span>
                                        {% elif resume.status == "4" %}
                                            <span> Статус : Черновик </span>
                                        {% elif resume.status == "5" %}
                                            <span> Статус : Скрыта </span>
                                        {% elif resume.status == "6" %}
                                            <span> Статус : Закрыта </span>
                                        {% elif resume.status == "9" %}
                                            <span> Статус : Удалена </span>
                                        {% endif %}
                                    </div>
                                </header>

                                <footer>
                                    <div class="header-meta">
                                        <span class="location">{{ resume.city }}</span>
                                        <span>Дата опубликования - {{ resume.created_at }}</span><br>
                                        <span>Дата обновления - {{ resume.updated_at }}</span><br>
                                    </div>
                                </footer>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
    <!-- END Main container -->
{% endblock %}

{% block footer %}{% endblock %}

templates/applicantapp/responce_job_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}

    {% block nav %}
    {% endblock %}

    {% block content %}
        <div class="container resume-container">

            <div class="form-group">
                <div class="input-group" style="text-align: center">
                    <span class="input-group-addon"><i class=""></i></span>
                    <img src="/media/{{ object.company.logo }}" alt="Logo" height="150">
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Название</i></span>
                    <span class="form-control form_control_centr_heigh"
                          id="id_headline"> {{ object }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-lg-6">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Классность</i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_first_name"> {{ object.get_grade_display }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group col-lg-6">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Категория</i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_surname">{{ object.get_category_display }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">Зарплата<i class=""></i></span>
                    <span type="number" min="0" class="form-control form_control_centr_heigh"
                          id="id_salary">{{ object.salary }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Дата рождения</i></span>
                    <span type="date" class="form-control form_control_centr_heigh"
                          id="id_date_of_birth">{{ object.date_of_birth }} </span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-lg-6">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""> Город </i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_city"> {{ object.city }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group col-lg-6">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""> Занятость </i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_city"> {{ object.get_employment_display }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon "><i class="">График работы</i></span>
                    <span class="form-control form_control_centr_heigh"
                          id="id_links"> {{ object.get_work_schedule_display }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Опыт работы</i></span>
                    <span class="form-control form_control_centr_heigh"
                          id="id_employment"> {{ object.get_experience_display }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Краткое описание</i></span>
                    <span class="form-control form_control_centr_heigh"
                          id="id_education_type"> {{ object.short_description }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Подробное описание:</i></span>
                    <span class="form-control form_control_centr_heigh"
                          id="id_work_schedule"> {{ object.description }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="">Навыки</i></span>
                    <span class="form-control form_control_centr_heigh"> {{ object.skills }}</span>
                    <span class="input-group-addon"><i class=""></i></span>
                </div>
            </div>


            <div>{% if messages %}
                {% for message in messages %}
                    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                {% endfor %}
            {% endif %}
            </div>

            <div class="row">
                <div class="form-group col-lg-12" style="text-align: center;">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {#                            <button class="btn btn-gray">Откликнуться</button>#}
                        {#                            <a href="{% url 'mainapp:invite_user' object.pk %}" class="btn btn-gray"> Откликнуться </a>#}
                        <form action="{% url 'mainapp:status_invite_update' object.id  %}" method="post" id="form_for_post" class="form-resume"
                              enctype="multipart/form-data"> {% csrf_token %}

                            {% if invite_count == 0 %}
                            <button type="submit" class="btn btn-gray btn-save" name="status" value="1">
                                Откликнуться
                            </button>
                            {% else %}
                            <span class="btn btn-gray btn-save"> Вы уже откликнулись на вакансию</span>
                            {% endif %}
                            <button type="submit" class="btn btn-gray btn-save" name="status" value="0">
                                Отклонить
                            </button>
                        </form>
                        <a href="{{ request.META.HTTP_REFERER|escape }}" class="btn btn-gray"> Назад </a>

                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>
            </div>

        </div>

    {% endblock %}

    {% block js %} {{ block.super }}
        <script defer src="{% static 'js/create_resume.js' %}"></script>
    {% endblock %}

{% endblock %}