moderapp/urls.py
from django.urls import path
from .views import ModerListPage, ModerateResume, ModerateCompany, ModerateJob, AddNews, UpdateNews

app_name = 'moderapp'

urlpatterns = [
    path('', ModerListPage.as_view(), name='moder_list_page'),
    path('add_news', AddNews.as_view(), name='add_news'),
    path('update_news/<int:pk>/', UpdateNews.as_view(), name='update_news'),
    path('moderate_resume/<int:pk>/', ModerateResume.as_view(), name='moderate_resume'),
    path('moderate_job/<int:pk>/', ModerateJob.as_view(), name='moderate_job'),
    path('moderate_company/<int:pk>/', ModerateCompany.as_view(), name='moderate_company'),
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
    path('moder/', include('moderapp.urls')),
    path('messenger/', include('messenger.urls'))

]

moderapp/models.py
from django.db import models


class News(models.Model):
    """
    News
    """

    class Meta:
        get_latest_by = '-created_at'
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    title = models.CharField(max_length=255, blank=False, verbose_name='Заголовок новости')
    body = models.TextField(blank=False, null=False, verbose_name='Текст новости')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __repr__(self):
        return self.title

    def __str__(self):
        return self.title

moderapp/forms.py
import django.forms as forms

from applicantapp.models import Resume
from moderapp.models import News
from companyapp.models import Job, Company


class AddUpdateNewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ['created_at', ]


class ResumeModerateForm(forms.ModelForm):
    class Meta:
        model = Resume
        exclude = ['user', 'views_count']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name not in ['status', 'moder_comment']:
                field.widget.attrs['readonly'] = True


class JobModerateForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['user', 'views_count']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name not in ['status', 'moder_comment']:
                field.widget.attrs['readonly'] = True


class CompanyModerateForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ['user', 'views_count']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

            if field_name not in ['status', 'moder_comment']:
                field.widget.attrs['readonly'] = True

moderapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.views.generic import TemplateView, UpdateView, CreateView

from applicantapp.models import Resume, Education, Experience
from companyapp.models import Job, Company
from moderapp.forms import ResumeModerateForm, JobModerateForm, CompanyModerateForm, AddUpdateNewsForm
from authapp.permissions import ModeratorPermissionMixin
from moderapp.models import News


class ModerListPage(LoginRequiredMixin, ModeratorPermissionMixin, TemplateView):
    """
    Moderator main page
    """
    template_name = 'moderapp/moder_main_page.html'

    def get_context_data(self, **kwargs):
        context = super(ModerListPage, self).get_context_data(**kwargs)
        context['news'] = News.objects.all().order_by('-created_at')
        context['resume_for_aprove'] = Resume.objects.filter(status=2)
        context['job_for_aprove'] = Job.objects.filter(status=2)
        context['company_for_aprove'] = Company.objects.filter(status=2)
        return context


class AddNews(LoginRequiredMixin, ModeratorPermissionMixin, CreateView):
    """
    Adding news
    """
    model = News
    form_class = AddUpdateNewsForm
    template_name = 'moderapp/add_news.html'
    success_url = '/moder'


class UpdateNews(LoginRequiredMixin, ModeratorPermissionMixin, UpdateView):
    """
    Read news details and update
    """
    model = News
    form_class = AddUpdateNewsForm
    template_name = 'moderapp/news_datail.html'
    success_url = '/moder'


class ModerateResume(LoginRequiredMixin, ModeratorPermissionMixin, UpdateView):
    """
    Moderate Resume
    """
    model = Resume
    form_class = ResumeModerateForm
    template_name = 'moderapp/obj_datail.html'
    success_url = '/moder'

    def get_context_data(self, **kwargs):
        data = super(ModerateResume, self).get_context_data(**kwargs)

        EducationFormSet = inlineformset_factory(
            Resume, Education, form=ResumeModerateForm, extra=1)
        ExperienceFormSet = inlineformset_factory(
            Resume, Experience, form=ResumeModerateForm, extra=1)

        if self.request.POST:
            data['education'] = EducationFormSet(self.request.POST, instance=self.object)
            data['experience'] = ExperienceFormSet(self.request.POST, instance=self.object)
        else:
            queryset_education = self.object.education.select_related()
            queryset_experience = self.object.experience.select_related()
            education_formset = EducationFormSet(
                instance=self.object, queryset=queryset_education)
            experience_formset = ExperienceFormSet(
                instance=self.object, queryset=queryset_experience)

            data['education'] = education_formset
            data['experience'] = experience_formset

        return data


class ModerateJob(LoginRequiredMixin, ModeratorPermissionMixin, UpdateView):
    """
    Moderate Job
    """
    model = Job
    form_class = JobModerateForm
    template_name = 'moderapp/obj_datail.html'
    success_url = '/moder'


class ModerateCompany(LoginRequiredMixin, ModeratorPermissionMixin, UpdateView):
    """
    Moderate Company
    """
    model = Company
    form_class = CompanyModerateForm
    template_name = 'moderapp/obj_datail.html'
    success_url = '/moder'

templates/moderapp/add_news.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}

    {% block content %}
    <div class="container">
            <form method="post" class="form-resume" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}

                <input type="submit" class="btn btn-success" value="Добавить">
                <a class="btn btn-primary" href="{% url 'moderapp:moder_list_page' %}">Вернуться</a>
            </form>
        </div>
    {% endblock %}

{% endblock %}

templates/moderapp/moder_main_page.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <header class="page-header bg-img size-lg">
        <div class="container no-shadow">
            <h1 class="text-center"> Резюме, вакансии, компании и новости </h1>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main container -->
    <main>
        <section class="no-padding-top bg-alt">
            <div class="container">
                <div class="row item-blocks-connected">


                    <div class="tab">
                        <button class="tablinks" onclick="openCity(event, 'Resume')">
                            Резюме {{ resume_for_aprove.count }}
                        </button>
                        <button class="tablinks" onclick="openCity(event, 'Job')">
                            Вакансии {{ job_for_aprove.count }}
                        </button>
                        <button class="tablinks" onclick="openCity(event, 'Company')">
                            Карточки компаний {{ company_for_aprove.count }}
                        </button>
                        <button class="tablinks news" onclick="openCity(event, 'News')">
                            Новости {{ news.count }}
                        </button>
                    </div>

                    <!-- Tab content -->

                    <div id="Resume" class="tabcontent">
                        <h3>Резюме</h3>
                        <span>
                            {% for resume in resume_for_aprove %}
                                <div class="col-xs-12">
                                    <div class="item-block">
                                        <header>
                                            <div class="hgroup">
                                                <a href="{% url 'moderapp:moderate_resume' resume.pk %}"><h4>{{ resume }}</h4></a>
                                            </div>
                                        </header>
                                    </div>
                                </div>
                            {% endfor %}
                        </span>
                    </div>

                    <div id="Job" class="tabcontent" style="display: none">
                        <h3>Вакансии</h3>
                        <span>
                            {% for job in job_for_aprove %}
                                <div class="col-xs-12">
                                    <div class="item-block">
                                        <header>
                                            <div class="hgroup">
                                                <a href="{% url 'moderapp:moderate_job' job.pk %}"><h4>{{ job }}</h4></a>
                                            </div>
                                        </header>
                                    </div>
                                </div>
                            {% endfor %}
                        </span>
                    </div>

                    <div id="Company" class="tabcontent" style="display: none">
                        <h3>Карточки компаний </h3>
                        <span>
                            {% for company in company_for_aprove %}
                                <div class="col-xs-12">
                                    <div class="item-block">
                                        <header>
                                            <div class="hgroup">
                                                <a href="{% url 'moderapp:moderate_company' company.pk %}"><h4>{{ company }}</h4></a>
                                            </div>
                                        </header>
                                    </div>
                                </div>
                            {% endfor %}
                        </span>
                    </div>

                    <div id="News" class="tabcontent" style="display: none">
                        <h3>Новости</h3>
                        <button><a href="{% url 'moderapp:add_news' %}">Добавить новость</a></button>
                        <span>
                            {% for item in news %}
                                <div class="col-xs-12">
                                    <div class="item-block">
                                        <header>
                                            <div class="hgroup">
                                                <a href="{% url 'moderapp:update_news' item.pk %}"><h4>{{ item }}</h4></a>
                                            </div>
                                        </header>
                                    </div>
                                </div>
                            {% endfor %}
                        </span>
                    </div>

                    <!-- END Tab content -->


                </div>
            </div>
        </section>
    </main>
    <!-- END Main container -->
{% endblock %}

{% block footer %} {% endblock %}

{#<img src="{% static 'img/logo-google.jpg' %}" alt="" >#}

templates/moderapp/news_datail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}


    {% block content %}
        <div class="container resume-container">
            <form method="post" class="form-resume" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}

                <input type="submit" class="btn btn-success" value="Сохранить изменения">
                <a class="btn btn-primary" href="{% url 'moderapp:moder_list_page' %}">Вернуться</a>
            </form>
        </div>
    {% endblock %}

{% endblock %}

templates/moderapp/obj_datail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}


    {% block content %}
        <div class="container resume-container">
            <form method="post" class="form-resume" enctype="multipart/form-data">
                {% csrf_token %}

                <h4>Общая информация</h4>

                {% for field in form %}
                    {% if field.name not in 'status moder_comment' %}
                        {{ field.label_tag }}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <hr>

                <h4>Образование</h4>

                {{ education.management_form }}
                {% for field in education.forms %}
                    {% if forloop.first %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <h4>Опыт работы</h4>

                {{ experience.management_form }}
                {% for field in experience.forms %}
                    {% if forloop.first %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <hr>

                {{ form.moder_comment.label_tag }}:
                {{ form.moder_comment }}

                <hr>

                <button type="submit" class="btn btn-success" name="status" value="3">
                    Одобрить и Опубликовать
                </button>
                <button type="submit" class="btn btn-danger" name="status" value="0">
                    Отказать в публикации
                </button>

                <hr>

                <a class="btn btn-primary" href="{% url 'moderapp:moder_list_page' %}">Вернуться</a>
            </form>
        </div>
    {% endblock %}

{% endblock %}