authapp/urls.py
from django.urls import path

from .views import SignUp, Login, Logout


app_name = 'authapp'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

mainapp/urls.py
from django.urls import path

from .views import Index, AllNews, NewsDetail, InviteView, InviteFromHr, statusInviteUpdate

app_name = 'mainapp'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('news/', AllNews.as_view(), name='news_all'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('ivnite/<int:job_id>/', InviteView.as_view(), name='invite_user'),
    path('invetofromhr/<int:resume>/', InviteFromHr.as_view(), name='invite_from_hr'),
    path('statusinvupdate/<int:pk>/', statusInviteUpdate, name='status_invite_update'),
]

messenger/urls.py
from django.urls import path

from messenger.views import DialogList, DialogDetail, create_message

app_name = 'messenger'

urlpatterns = [
    path('', DialogList.as_view(), name='dialog_list'),
    path('dialog_detail/<int:pk>', DialogDetail.as_view(), name='dialog_detail'),
    path('create_msg/<int:pk>', create_message, name='create_message'),


]

moderapp/urls.py
from django.urls import path
from .views import ModerListPage, ModerateResume, ModerateCompany, ModerateJob, AddNews, UpdateNews

app_name = 'moderapp'

urlpatterns = [
    path('', ModerListPage.as_view(), name='moder_list_page'),
    path('add_news', AddNews.as_view(), name='add_news'),
    path('update_news/<int:pk>/', UpdateNews.as_view(), name='update_news'),
    path('moderate_resume/<int:pk>/', ModerateResume.as_view(), name='moderate_resume'),
    path('moderate_job/<int:pk>/', ModerateJob.as_view(), name='moderate_job'),
    path('moderate_company/<int:pk>/', ModerateCompany.as_view(), name='moderate_company'),
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
    path('moder/', include('moderapp.urls')),
    path('messenger/', include('messenger.urls'))

]

templates/inc/applicant_header_menu.html
<p class="lead text-center">
    <a href="{% url 'applicantapp:resume-list' %}"> Список резюме |</a>
    <a href="{% url 'applicantapp:favorites-job-list' %}"> Избранное |</a>
    <a href="{% url 'applicantapp:job_search_list' %}"> Поиск вакансий |</a>
    <a href="{% url 'applicantapp:responce_resume_list' %}"> Приглашения |</a>
    <a href="{% url 'messenger:dialog_list' %}"> Сообщения |</a>
</p>

templates/inc/company_header_menu.html
<p class="lead text-center">
    <a href="{% url 'companyapp:card' user.company.pk %}">| Карточка компании |</a>
    <a href="{% url 'companyapp:favorites-resume-list' %}"> Избранное |</a>
    <a href="{% url 'companyapp:job-list' %}"> Список вакансий |</a>
    <a href="{% url 'companyapp:resume_search' %}"> Поиск резюме |</a>
    <a href="{% url 'companyapp:responce_recrut_list' %}"> Отклики |</a>
    <a href="{% url 'messenger:dialog_list' %}"> Сообщения |</a>
</p>

templates/inc/footer.html
<!-- Site footer -->
<footer class="site-footer">

    <!-- Top section -->
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h6> О проекте </h6>
                <p class="text-justify">
                    Проект для поиска IT  специалистов и размещения вакансии для IT специалистов.
                </p>
            </div>


        </div>
        <hr>
    </div>
    <!-- END Top section -->

    <!-- Bottom section -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyrights &copy; 2021 All Rights Reserved by
                    <a href="#">GeekStaff</a>.
                </p>
            </div>


        </div>
    </div>
    <!-- END Bottom section -->

</footer>
<!-- END Site footer -->

templates/inc/header.html
<!-- Site header -->
<header class="site-header size-lg text-center">
    <div class="container">
        <div class="col-xs-12">
            <br><br>
            <h2>Мы предлагаем <mark>1,259</mark> IT-вакансий прямо сейчас!</h2>
            <h5 class="font-alt">Найдите работу мечты за минуту.</h5>
            <br><br>
        </div>

        <!-- Facts -->
        <div class="row">
    
            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">1259</span></p>
                <h6>Вакансий</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">4502</span></p>
                <h6>Соискателей</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">9010</span></p>
                <h6>Резюме</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">212</span></p>
                <h6>IT-компаний</h6>
            </div>
    
        </div>
        <!-- END Facts -->
    </div>
</header>
<!-- END Site header -->

templates/inc/index-jobs.html
{% load static %}

<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Недавние вакансии</h2>
            <p>Последние предложения о работе, размещённые на сайте</p>
        </header>

        <div class="row item-blocks-connected">

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                        <div class="hgroup">
                            <h4>Сеньор Frontend разработчик</h4>
                            <h5>Google</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Калифорния</span>
                            <span class="label label-success">Полная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-linkedin.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>Software Engineer (Entry or Senior)</h4>
                            <h5>Linkedin</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Ливермор, Калифорния</span>
                            <span class="label label-success">Удалённо</span>
                            <span class="label label-warning">Частичная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-envato.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>FullStack Web разработчик</h4>
                            <h5>Envato</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Сан Франциско, Калифорния</span>
                            <span class="label label-info">Фриланс</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>Web разработчик</h4>
                            <h5>Facebook</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Лексингтон, Массачусетс</span>
                            <span class="label label-danger">Стажировка</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                        <div class="hgroup">
                            <h4>Сеньор SQL Server разработчик</h4>
                            <h5>Microsoft</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Пало Альта, Калифорния</span>
                            <span class="label label-success">Удалённо</span>
                            <span class="label label-success">Полная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->
            
        </div>
        <br /><br />
        <p class="text-center"><a class="btn btn-info" href="#">Больше вакансий</a></p>
    </div>
</section>

templates/inc/index-news.html
<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Последние Новости</h2>
            <p>Самая свежая информация из мира IT</p>
        </header>

        <div class="row item-blocks-connected">

            {% for item in object_list %}
                {% include 'inc/news_item.html' %}
            {% endfor %}


        </div>
        <br /><br />
        <p class="text-center"><a class="btn btn-info" href="{% url 'mainapp:news_all' %}">Все новости</a></p>
    </div>
</section>

templates/inc/index-partners.html
{% load static %}

<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Наши партнёры</h2>
            <p>IT-Компании</p>
        </header>

        <div class="category-grid">

            <a href="#">
                <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                <h6>Google</h6>
                <p>Цель компании – упорядочить всю информацию и сделать ее доступной</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                <h6>Facebook</h6>
                <p>Give people the power to build community and bring the world closer together</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                <h6>Microsoft</h6>
                <p>Microsoft – обеспечивает продуктивность в мире, где царят мобильность и облако</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                <h6>Microsoft</h6>
                <p>Microsoft – обеспечивает продуктивность в мире, где царят мобильность и облако</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                <h6>Google</h6>
                <p>Цель компании – упорядочить всю информацию и сделать ее доступной</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                <h6>Facebook</h6>
                <p>Give people the power to build community and bring the world closer together</p>
            </a>

        </div>
    </div>
</section>

templates/inc/job_list.html
{% for jobs in object_list %}
<div class="col-xs-12">
    <div class="item-block">
        <header>
            <a href="#"><img src="/img/logo-google.jpg" alt=""></a>
            <div class="hgroup">
                <h5><a href="{% url 'applicantapp:job-list-detail' jobs.pk %}">{{ jobs }} </a></h5>
                <h5><a href=#>Google</a></h5>
            </div>
            <div class="header-meta">
                <span ><i class="fa fa-map-marker"></i> {{ jobs.city }} </span><br>
                <span class="rate">{{ jobs.salary }} руб. </span>
            </div>
        </header>

        <footer>

        </footer>
    </div>
</div>
{% endfor %}

templates/inc/nav-menu.html
{#<ul class="nav-menu">#}
{##}
{##}
{#    {% if user.role == "REC" %}#}
{#        <li>#}
{#            <a href="{% url 'applicantapp:job_search_list' %}">Вакансии </a>#}
            {#        <ul>#}
            {#            <li><a href="{% url 'mainapp:job_search' %}">Поиск вакансий</a></li>#}
            {#            <li><a href="#">Подробная вакансия</a></li>#}
            {#            <li><a href="#">Разместить вакансию</a></li>#}
            {#            <li><a href="{% url 'mainapp:job_list' %}">Управление вакансиями</a></li>#}
            {#        </ul>#}
{#        </li>#}
{#    {% endif %}#}
{##}
{#    {% if user.role == "HR" %}#}
{##}
{##}
{#        <li>#}
{#            <a href="{% url 'companyapp:resume-list' %}">Список резюме</a>#}
            {#        <ul>#}
            {#            <li><a href="{% url 'companyapp:resume-list'%}">Список резюме</a></li>#}
            {#            <li><a href="{% url 'companyapp:resume-list'%}">Список резюме</a></li>#}
            {#            <li><a href="{% url 'applicantapp:createresume'%}">Создать резюме</a></li>#}
            {#            <li><a href="{% url 'applicantapp:resume-list'%}">Управление резюме</a></li>#}
            {#        </ul>#}
{#        </li>#}
{#    {% endif %}#}
    {#    <li>#}
    {#        <a href="#">IT-Компании</a>#}
    {#        <ul>#}
    {#            <li><a href="#">Найти IT-компанию</a></li>#}
    {#            <li><a href="#">Описание компании</a></li>#}
    {#            <li><a href="#">Создать компанию</a></li>#}
    {#            <li><a href="#">Управление компаниями</a></li>#}
    {#        </ul>#}
    {#    </li>#}
    {#    <li>#}
    {#        <a href="#">Информация</a>#}
    {#        <ul>#}
    {#            <li><a href="#">О нас</a></li>#}
    {#            <li><a href="#">Контакты</a></li>#}
    {#            <li><a href="#">F.A.Q.</a></li>#}
    {#        </ul>#}
    {#    </li>#}
{#</ul>#}

templates/inc/nav.html
{% load static %}

<!-- Navigation bar -->
<nav class="navbar">
    <div class="container">

        <!-- Logo -->
        <div class="pull-left">
            <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

            <div class="logo-wrapper">
                <a class="logo" href="{% url 'mainapp:index' %}"><img src="{% static 'img/logo1.png' %}" alt="logo"></a>
            </div>
        </div>
        <!-- END Logo -->

        <!-- User account -->
        <div class="pull-right">
            <div class="dropdown user-account">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <img src="{% static 'img/logo-ava.jpg' %}" alt="avatar">
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    {% if user.is_authenticated %}
                        <li style="padding-left:8px"> {{ user.email }} </li>
                        {% if user.is_superuser %} <li><a href="/admin/">Админка</a></li> {% endif %}
                        {% if user.is_staff %} <li><a href="{% url 'moderapp:moder_list_page' %}">Модерировать</a></li> {% endif %}
                        {% if user.role == 'HR' %} 
                            <li><a href="{% url 'companyapp:profile' user.pk %}">Личный кабинет</a></li> 
                        {% endif %}
                        {% if user.role == 'REC' and not user.is_staff %} 
                            <li><a href="{% url 'applicantapp:profile' user.pk %}">Личный кабинет</a></li> 
                        {% endif %}
                        <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'authapp:login' %}">Войти</a></li>
                        <li><a href="{% url 'authapp:signup' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- END User account -->

        <!-- Navigation menu -->
        {% include 'inc/nav-menu.html' %}
        <!-- END Navigation menu -->
    </div>
</nav>

templates/inc/news_item.html
<!-- News item -->
<div class="col-xs-12">
    <a class="item-block" href="{% url 'mainapp:news_detail' item.pk %}">
        <header>
            <div class="hgroup">
                <h4>{{ item.title }}</h4>
                <h5>{{ item.body|slice:80 }}</h5>
            </div>
            <div class="header-meta">
                <div class="ti-time"> {{ item.created_at }}</div>
                <span class="news label label-success">Подробнее...</span>
            </div>
        </header>
    </a>
</div>
<!-- END News item -->

templates/inc/resume_list_inc.html
{% for resume in object_list %}
<div class="col-xs-12">
    <div class="item-block">
        <header>
            <div class="hgroup">
                <h5><a href="{% url 'companyapp:resume-list-detail' resume.pk %}">{{ resume }} </a></h5>
            </div>
            <div class="header-meta">
                <span ><i class="fa fa-map-marker"></i> {{ resume.city }} </span><br>
                <span class="rate">{{ resume.salary }} руб. </span>
            </div>
        </header>

        <footer>
            <div class="header-meta">
                <span class="location">{{ resume.city }}</span>
                <span>Дата опубликования - {{ resume.created_at }}</span><br>
                <span>Дата обновления - {{ resume.updated_at }}</span><br>
            </div>
        </footer>
    </div>
</div>
{% endfor %}